baseURL: /

publishDir: "public"
languageCode: en-us
title: "ZOOOOOM.US"

canonifyURLs: true
enableRobotsTXT: true
sectionPagesMenu: main

params:
  ga_id: "UA-70650-50"
  description: "A screen saver for these anxious times"
  keywords: "screensaver, video conferencing, humor, harper reed, tolar, george bush"
  cachebuster: ""
  name: "Tolar and Harper"
  email: happiness@zooooom.us
  icon: fa-webcam
  download_link: https://github.com/harperreed/zooooom.us/releases/download/Build-3/Zooooom-3.zip


disableKinds:
  - section
  - section
  - taxonomy
  - taxonomyTerm
  - rss
  - section
  - page

