[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = "max-age=43200"

[[headers]]
  for = "/config.json"
  [headers.values]
	cache-control = "max-age=43200"

[[headers]]
  for = "/media/*"
  [headers.values]
	cache-control = "max-age=604800"
