[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/download"
  to = "https://github.com/rhaining/zooooom-screensaver/releases/download/v1.1-2/Zooooom-1.1-2.zip"
  status = 302
