[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/download"
  to = "https://github.com/rhaining/zooooom-screensaver/releases/download/v1.2/Zooooom-1.2-1.zip"
  status = 302
  
[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

[[headers]]
  for = "/media/*"
  [headers.values]
	cache-control = "max-age=604800"
